name: copy md to docs

on:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/**"
  workflow_dispatch:

jobs:
  document-updated:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.MY_GITHUB_APP_ID }}
          private_key: ${{ secrets.MY_GITHUB_APP_PRIVATE_KEY }}
      - name: Create Github dispatch event
        run: |
          curl --request POST 'https://api.github.com/repos/Yuta-31/mldi_public_document/dispatches' \
          --header 'Autherization: Bearer ${{ steps.generate_token.outputs.token }}' \
          --header 'Content-Type: application/json' \
          --data-raw '{
            "event_type": "document-updated"
          }'
